authorization/urls.py
from django.urls import path
from .views import IndexView, LoginView, RegisterView, LogoutView

app_name = "authorization"
urlpatterns = [
    path('', view=IndexView.as_view(), name="index"),
    path('login', view=LoginView.as_view(), name="login"),
    path('logout', view=LogoutView.as_view(), name="logout"),
    path('register', view=RegisterView.as_view(), name="register"),
]

main/urls.py
from django.urls import path
from .views import HomeView

app_name = "main"
urlpatterns = [
    path("", view=HomeView.as_view(), name="home"),
]

authorization/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from .utils import user_model_fields_data, PASSWORD_ATTRIBUTES


DEFAULT_ATTRIBUTES = {"class": "form-field"}

class LoginForm(forms.Form):
    """Form that provides fields necessary to authenticate user.

    Attributes:
        username: username field of user to authenticate
        password: password field of user to authenticate
    """
    username = forms.CharField(
        label="Username", required=True,
        widget=forms.TextInput(
            {"id": "id_login_username", **DEFAULT_ATTRIBUTES}
        )
    )
    password = forms.CharField(
        label="Password", required=True,
        widget=forms.PasswordInput(
            {"id": "id_login_password", **DEFAULT_ATTRIBUTES}
        )
    )


class RegisterForm(forms.ModelForm):
    """Form that provides fields necessary to create new user.

    Attributes:
        password: password field of new user
        password_repeat: repeat password field of new user
    """
    password = forms.CharField(
        label="Password", required=True,
        widget=forms.PasswordInput(
            {**PASSWORD_ATTRIBUTES, **DEFAULT_ATTRIBUTES}
        )
    )
    password_repeat = forms.CharField(
        label="Repeat password", required=True,
        widget=forms.PasswordInput(
            {**PASSWORD_ATTRIBUTES, **DEFAULT_ATTRIBUTES}
        )
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Provide attributes for fields that has been create automatically
        # based on meta
        for field_name in user_model_fields_data:
            widget, label, field_attrs = user_model_fields_data[field_name]
            self.fields[field_name].required = True
            self.fields[field_name].label = label
            self.fields[field_name].widget = widget(
                {**DEFAULT_ATTRIBUTES, **field_attrs}
            )

    class Meta:
        model = User
        fields = ("email", "username", "first_name", "last_name")

    def clean(self):
        """Checks if password and password repeat field have the same value."""
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_repeat = cleaned_data.get("password_repeat")

        if password and password_repeat and password != password_repeat:
            self.add_error("password", "Passwords are not the same.")

    def clean_email(self):
        """Checks if user with passed e-mail value already exists.

        Returns:
            E-mail address value passed to form
        Raises:
            Validation error with message that e-mail address is not available
        """
        email = self.cleaned_data["email"]

        if User.objects.filter(email=email).count() > 0:
            raise forms.ValidationError("E-mail address is already used.")

        return email

    def clean_username(self):
        """Checks if user with passed username value already exists.

        Returns:
            Username value passed to form
        Raises:
            Validation error with message that username is not available
        """
        username = self.cleaned_data["username"]
        self.validate_length_and_pattern(
            "username", username, user_model_fields_data, forms.ValidationError
        )

        if User.objects.filter(username=username).count() > 0:
            raise forms.ValidationError("Username is already used.")

        return username

    def clean_first_name(self):
        """Checks if passed first name value matches proper pattern and length.

        Returns:
            First name value passed to form
        """
        first_name = self.cleaned_data["first_name"]
        self.validate_length_and_pattern(
            "first_name", first_name, user_model_fields_data,
            forms.ValidationError
        )

        return first_name.strip().capitalize()

    def clean_last_name(self):
        """Checks if passed last name value matches proper pattern and length.

        Returns:
            Last name value passed to form
        """
        last_name = self.cleaned_data["last_name"]
        self.validate_length_and_pattern(
            "last_name", last_name, user_model_fields_data,
            forms.ValidationError
        )
        last_name = re.sub(r"[  ]+", " ", last_name.strip())

        return last_name.title()

    def clean_password(self):
        """Checks if passed password value matches proper pattern and length.

        Returns:
            Password value passed to form
        """
        password = self.cleaned_data["password"]
        password_data = {"password": (0, "Password", PASSWORD_ATTRIBUTES)}

        self.validate_length_and_pattern(
            "password", password, password_data, forms.ValidationError
        )

        return password

    @staticmethod
    def validate_length_and_pattern(name, value, field_info, error):
        """Validates length of field value and checks if value matches pattern.

        Args:
            name: name of field
            value: value of field
            field_info: tuple with info about particular field (field type,
            label text and field attributes)
            error: Exception class to raise if error has occured
        Raises:
            Django form/DRF serializer validation error raised when value has
            invalid length or doesn't match the pattern.
        """
        # Getting field attributes
        field_data = field_info[name][-1]

        minlen = field_data["minlength"]
        maxlen = field_data.get("maxlength")
        pattern = field_data["pattern"]

        if len(value) < minlen or (maxlen and len(value) > maxlen):
            err = RegisterForm.prepare_len_error(name, minlen, maxlen)
            raise error(err)
        elif not re.match(pattern, value):
            raise error(field_data["title"])

    @staticmethod
    def prepare_len_error(field_name, minlen, maxlen):
        """Prepares field invalid length error message.

        Args:
            field_name: name of field
            minlen: required minimum length of field value
            maxlen: required maximum length of field value
        """
        field_name = field_name.capitalize().replace("_", " ")
        err = f"{field_name} needs to have at least {minlen} "

        if maxlen is not None and maxlen > 0:
            err += f"and at most {maxlen} "

        err += "characters."

        return err

authorization/views.py
from django.views import View
from django.views.generic import TemplateView, FormView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.shortcuts import redirect
from .forms import LoginForm, RegisterForm
from .models import Profile
from .utils import LoginRedirectMixin


class IndexView(LoginRedirectMixin, TemplateView):
    """Template view with basic info about site and login/register forms."""
    template_name = "authorization/index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["login_form"] = LoginForm
        context["register_form"] = RegisterForm

        return context


class LoginView(LoginRedirectMixin, FormView):
    """Form view that handles logging user in."""
    template_name = "authorization/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("main:home")

    def form_valid(self, form):
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        user = authenticate(username=username, password=password)

        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            login_msg = "Username and/or password incorrect. Try again."
            messages.error(self.request, login_msg)
            return redirect("authorization:login")


class RegisterView(LoginRedirectMixin, FormView):
    """Form view that handles creating new user."""
    template_name = "authorization/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("main:home")

    def form_valid(self, form):
        # Delete 'password_repeat' field from data, because User model doesn't
        # have field with that name.
        del form.cleaned_data["password_repeat"]

        try:
            new_user = User.objects.create_user(**form.cleaned_data)
            new_profile = Profile.objects.create(user=new_user)

            success_msg = "Account has been successfully created."
            messages.success(self.request, success_msg)
        except Exception:
            error_msg = "Oops, something went wrong. Try again later."
            messages.error(self.request, error_msg)

        return super().form_valid(form)


class LogoutView(View):
    """View that handles logging user out."""
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            logout_msg = "Your account has been logged out."
            messages.success(self.request, logout_msg)

        return redirect(reverse_lazy("authorization:login"))


def handler404(request):
    return redirect(reverse("authorization:index"))

templates/authorization/index.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Welcome - Esqola{% endblock %}

{% block style %}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block content %}
<header class="index-header">
  <div class="index-header__logo">
    <div class="logo-owl logo-owl--animation">
      <div class="logo-owl__image"></div>
    </div>
    <h1 class="logo__title">Esqola</h1>
  </div>
</header>
<main>
  <section class="devices">
    <img src="{% static 'img/desk.png' %}" class="devices__image devices__image--down" alt="desk">
    <img src="{% static 'img/phone.png' %}" class="devices__image devices__image--up" alt="phone">
    <img src="{% static 'img/lap.png' %}" class="devices__image devices__image--down" alt="laptop">
    <h2 class="devices__heading">
      Learn <strong>anywhere</strong>, on <strong>anything</strong>.
    </h2>
  </section>
  <section class="rules">
    <header class="rules__header">
      <h2 class="rules__heading">
        So, why should you use <strong>ESQOLA</strong>?
      </h2>
    </header>
    <article class="rule">
      <h3 class="rule__heading">
        <i class="material-icons rule__icon pink-circle">smartphone</i> Accessibility
      </h3>
      <p class="rule__paragraph">
         Desktop, smartphone, laptop, tablet - if you have a browser on your device and access to the internet, that's everything you need to start journey with <strong>Esqola</strong>.
      </p>
    </article>
    <article class="rule">
      <h3 class="rule__heading">
        <i class="material-icons rule__icon pink-circle">speaker_notes</i> Discussion
      </h3>
      <p class="rule__paragraph">
        <i>Tú no entiendes español</i> or english grammar seems a little bit too complicated for you? <i>No problemo</i>, ask friends from your virtual class for help.
          </p>
    </article>
    <article class="rule">
      <h3 class="rule__heading">
        <i class="material-icons rule__icon pink-circle">school</i> Education
      </h3>
      <p class="rule__paragraph">
        Games are designed with purpose of  allowing students to gain as much knowleadge as possible. Also, teachers have tools to check students scores.
          </p>
    </article>
    <article class="rule">
      <h3 class="rule__heading">
        <i class="material-icons rule__icon pink-circle">sentiment_very_satisfied</i> Enjoyment
      </h3>
      <p class="rule__paragraph">
        Learning and having fun. It's our job to provide games and modules that students don't consider as a classwork, but great way of spending time.
      </p>
    </article>
  </section>
  <section class="game-example">
    <div class="game-example__group">
      <h2 class="game-example__heading game-example__heading--primary">
        Let's give it a try, show us what you got!
      </h2>
      <h3 class="game-example__heading game-example__heading--secondary">
        Connect english words with portuguese translation.
      </h3>
    </div>
    <div class="game-example__language">
      <img class="game-setup-flag" src="{% static '/img/brazil-flag.png' %}" alt="brazil">
      <div class="game-words" id="portuguese">
        <div class="game-word no-select">formiga</div>
        <div class="game-word no-select">jogador</div>
        <div class="game-word no-select">pão</div>
        <div class="game-word no-select">irmão</div>
        <div class="game-word no-select">futebol</div>
        <div class="game-word no-select">maçã</div>
        <div class="game-word no-select">amigo</div>
        <div class="game-word no-select">bonita</div>
        <div class="game-word no-select">mulher</div>
      </div>
    </div>
    <div class="game-example__language">
      <img class="game-setup-flag" src="{% static '/img/united-kingdom-flag.png' %}" alt="united kingdom">
      <div class="game-words" id="english">
        <div class="game-word no-select">bread</div>
        <div class="game-word no-select">player</div>
        <div class="game-word no-select">beautiful</div>
        <div class="game-word no-select">football</div>
        <div class="game-word no-select">friend</div>
        <div class="game-word no-select">apple</div>
        <div class="game-word no-select">ant</div>
        <div class="game-word no-select">woman</div>
        <div class="game-word no-select">brother</div>
      </div>
    </div>
    <article class="game-example__success">
      <h3 class="game-example__success--score">
        <i class="material-icons game-example__success--icon">timer</i> | <span id="score"></span>
      </h3>
      <h4 class="game-example__success--info">Good job, keep it up!</h4>
    </article>
  </section>
  <section class="index-forms">
    <header class="rules__header index-forms__header">
      <h2 class="rules__heading">
        What would you like to do <strong>now</strong>?
      </h2>
    </header>
    <article class="index-forms__wrapper">
      <h2 class="index-forms__heading">Log in</h2>
      <form action="{% url 'authorization:login' %}" method="POST">
        {% csrf_token %}
        {% for field in login_form %}
        <label class="index-forms__label">{{ field.label }}</label>
        <div class="form-field__wrapper form-field__wrapper--index">
          {{ field }}
        </div>
        {% endfor %}
        <button class="index-forms__button">Send</button>
      </form>
    </article>
    <article class="index-forms__wrapper">
      <h2 class="index-forms__heading">Sign up</h2>
      <form action="{% url 'authorization:register' %}" method="POST">
        {% csrf_token %}
        {% for field in register_form %}
        {% include './partials/index_form.html' %}
        {% endfor %}
        <button class="index-forms__button">Send</button>
      </form>
    </article>
  </section>
</main>
{% endblock %}

{% block script %}
<script src="{% static '/dist/bundle-auth.js' %}"></script>
{% endblock %}

templates/authorization/login.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Login - Esqola{% endblock %}

{% block content %}
{% include "./partials/header.html" %}
<main>
  <section class="auth-section">
    <h2 class="index-forms__heading auth-section__heading">
      <span class="pink-circle auth-section__pink_circle">Sign in</span>
    </h2>
    <form action="{% url 'authorization:login' %}" method="POST" class="auth-form">
      {% csrf_token %}
      {% for msg in messages %}
        <div class="auth-message {% if msg.tags %}auth-message--{{ msg.tags }}{% endif %}">
          {{ msg }}
        </div>
      {% endfor %}

      {% for field in form %}
      {% include './partials/auth_form.html' %}
      {% endfor %}
      <button class="index-forms__button">Send</button>
    </form>
    <a href="{% url 'authorization:register' %}" class="auth-link">
      <div class="rules__header rules__header--auth">
        Do you want to create an account? Click here.
      </div>
    </a>
  </section>
</main>
{% endblock %}

{% block script %}
<script src="{% static '/dist/bundle-auth.js' %}"></script>
{% endblock %}

templates/authorization/register.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Register - Esqola{% endblock %}

{% block content %}
{% include "./partials/header.html" %}
<main>
  <section class="auth-section">
    <h2 class="index-forms__heading auth-section__heading">
      <span class="pink-circle auth-section__pink_circle">Sign up</span>
    </h2>
    <form action="{% url 'authorization:register' %}" method="POST" class="auth-form">
      {% csrf_token %}

      {% for field in form %}
        {% for error in field.errors %}
          <div class="auth-message auth-message--error">
            {{ error }}
          </div>
        {% endfor %}
        {% include './partials/auth_form.html' %}
      {% endfor %}
      <button class="index-forms__button">Send</button>
    </form>
    <a href="{% url 'authorization:login' %}" class="auth-link">
      <div class="rules__header rules__header--auth">
        Do you already have an account? Log in here.
      </div>
    </a>
  </section>
</main>
{% endblock %}

{% block script %}
<script src="{% static '/dist/bundle-auth.js' %}"></script>
{% endblock %}